package test

// Code generated by github.com/algorand/msgp DO NOT EDIT.

import (
	"sort"

	"github.com/algorand/msgp/msgp"
)

// The following msgp objects are implemented in this file:
// CanonicalTestStruct
//          |-----> (*) MarshalMsg
//          |-----> (*) CanMarshalMsg
//          |-----> (*) UnmarshalMsg
//          |-----> (*) CanUnmarshalMsg
//          |-----> (*) Msgsize
//          |-----> (*) MsgIsZero
//          |-----> CanonicalTestStructMaxSize()
//
// SortableUint64
//        |-----> MarshalMsg
//        |-----> CanMarshalMsg
//        |-----> (*) UnmarshalMsg
//        |-----> (*) CanUnmarshalMsg
//        |-----> Msgsize
//        |-----> MsgIsZero
//        |-----> SortableUint64MaxSize()
//
// testSlice
//     |-----> MarshalMsg
//     |-----> CanMarshalMsg
//     |-----> (*) UnmarshalMsg
//     |-----> (*) CanUnmarshalMsg
//     |-----> Msgsize
//     |-----> MsgIsZero
//     |-----> TestSliceMaxSize()
//

// MarshalMsg implements msgp.Marshaler
func (z *CanonicalTestStruct) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0004Len := uint32(8)
	var zb0004Mask uint16 /* 9 bits */
	if (*z).A == 0 {
		zb0004Len--
		zb0004Mask |= 0x2
	}
	if ((*z).B.B1 == false) && ((*z).B.B2 == "") {
		zb0004Len--
		zb0004Mask |= 0x4
	}
	if len((*z).C) == 0 {
		zb0004Len--
		zb0004Mask |= 0x8
	}
	if (*z).D == "" {
		zb0004Len--
		zb0004Mask |= 0x10
	}
	if (*z).E == ([2]string{}) {
		zb0004Len--
		zb0004Mask |= 0x20
	}
	if len((*z).G) == 0 {
		zb0004Len--
		zb0004Mask |= 0x40
	}
	if (*z).H == 0 {
		zb0004Len--
		zb0004Mask |= 0x80
	}
	if (*z).I == 0 {
		zb0004Len--
		zb0004Mask |= 0x100
	}
	// variable map header, size zb0004Len
	o = append(o, 0x80|uint8(zb0004Len))
	if zb0004Len != 0 {
		if (zb0004Mask & 0x2) == 0 { // if not empty
			// string "a"
			o = append(o, 0xa1, 0x61)
			o = msgp.AppendInt64(o, (*z).A)
		}
		if (zb0004Mask & 0x4) == 0 { // if not empty
			// string "b"
			o = append(o, 0xa1, 0x62)
			// omitempty: check for empty values
			zb0005Len := uint32(2)
			var zb0005Mask uint8 /* 3 bits */
			if (*z).B.B1 == false {
				zb0005Len--
				zb0005Mask |= 0x2
			}
			if (*z).B.B2 == "" {
				zb0005Len--
				zb0005Mask |= 0x4
			}
			// variable map header, size zb0005Len
			o = append(o, 0x80|uint8(zb0005Len))
			if (zb0005Mask & 0x2) == 0 { // if not empty
				// string "b1"
				o = append(o, 0xa2, 0x62, 0x31)
				o = msgp.AppendBool(o, (*z).B.B1)
			}
			if (zb0005Mask & 0x4) == 0 { // if not empty
				// string "b2"
				o = append(o, 0xa2, 0x62, 0x32)
				o = msgp.AppendString(o, (*z).B.B2)
			}
		}
		if (zb0004Mask & 0x8) == 0 { // if not empty
			// string "c"
			o = append(o, 0xa1, 0x63)
			o = msgp.AppendBytes(o, (*z).C)
		}
		if (zb0004Mask & 0x10) == 0 { // if not empty
			// string "d"
			o = append(o, 0xa1, 0x64)
			o = msgp.AppendString(o, (*z).D)
		}
		if (zb0004Mask & 0x20) == 0 { // if not empty
			// string "e"
			o = append(o, 0xa1, 0x65)
			o = msgp.AppendArrayHeader(o, 2)
			for zb0001 := range (*z).E {
				o = msgp.AppendString(o, (*z).E[zb0001])
			}
		}
		if (zb0004Mask & 0x40) == 0 { // if not empty
			// string "g"
			o = append(o, 0xa1, 0x67)
			if (*z).G == nil {
				o = msgp.AppendNil(o)
			} else {
				o = msgp.AppendMapHeader(o, uint32(len((*z).G)))
			}
			zb0002_keys := make([]SortableUint64, 0, len((*z).G))
			for zb0002 := range (*z).G {
				zb0002_keys = append(zb0002_keys, zb0002)
			}
			sort.Sort(SortUint64(zb0002_keys))
			for _, zb0002 := range zb0002_keys {
				zb0003 := (*z).G[zb0002]
				_ = zb0003
				o = zb0002.MarshalMsg(o)
				o = msgp.AppendUint64(o, zb0003)
			}
		}
		if (zb0004Mask & 0x80) == 0 { // if not empty
			// string "h"
			o = append(o, 0xa1, 0x68)
			o = msgp.AppendInt64(o, (*z).H)
		}
		if (zb0004Mask & 0x100) == 0 { // if not empty
			// string "i"
			o = append(o, 0xa1, 0x69)
			o = msgp.AppendInt64(o, (*z).I)
		}
	}
	return
}

func (_ *CanonicalTestStruct) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(*CanonicalTestStruct)
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CanonicalTestStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0004 int
	var zb0005 bool
	zb0004, zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
	if _, ok := err.(msgp.TypeError); ok {
		zb0004, zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0004 > 0 {
			zb0004--
			(*z).A, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "A")
				return
			}
		}
		if zb0004 > 0 {
			zb0004--
			var zb0006 int
			var zb0007 bool
			zb0006, zb0007, bts, err = msgp.ReadMapHeaderBytes(bts)
			if _, ok := err.(msgp.TypeError); ok {
				zb0006, zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "struct-from-array", "B")
					return
				}
				if zb0006 > 0 {
					zb0006--
					(*z).B.B1, bts, err = msgp.ReadBoolBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "struct-from-array", "B", "struct-from-array", "B1")
						return
					}
				}
				if zb0006 > 0 {
					zb0006--
					(*z).B.B2, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "struct-from-array", "B", "struct-from-array", "B2")
						return
					}
				}
				if zb0006 > 0 {
					err = msgp.ErrTooManyArrayFields(zb0006)
					if err != nil {
						err = msgp.WrapError(err, "struct-from-array", "B", "struct-from-array")
						return
					}
				}
			} else {
				if err != nil {
					err = msgp.WrapError(err, "struct-from-array", "B")
					return
				}
				if zb0007 {
					(*z).B = struct {
						_struct struct {
						} `codec:",omitempty,omitemptyarray"`
						B1 bool   `codec:"b1,omitempty"`
						B2 string `codec:"b2,omitempty"`
					}{}
				}
				for zb0006 > 0 {
					zb0006--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "struct-from-array", "B")
						return
					}
					switch string(field) {
					case "b1":
						(*z).B.B1, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "struct-from-array", "B", "B1")
							return
						}
					case "b2":
						(*z).B.B2, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "struct-from-array", "B", "B2")
							return
						}
					default:
						err = msgp.ErrNoField(string(field))
						if err != nil {
							err = msgp.WrapError(err, "struct-from-array", "B")
							return
						}
					}
				}
			}
		}
		if zb0004 > 0 {
			zb0004--
			var zb0008 int
			zb0008, err = msgp.ReadBytesBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "C")
				return
			}
			if zb0008 > 8 {
				err = msgp.ErrOverflow(uint64(zb0008), uint64(8))
				return
			}
			(*z).C, bts, err = msgp.ReadBytesBytes(bts, (*z).C)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "C")
				return
			}
		}
		if zb0004 > 0 {
			zb0004--
			(*z).D, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "D")
				return
			}
		}
		if zb0004 > 0 {
			zb0004--
			var zb0009 int
			zb0009, _, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "E")
				return
			}
			if zb0009 > 2 {
				err = msgp.ArrayError{Wanted: 2, Got: zb0009}
				return
			}
			for zb0001 := 0; zb0001 < zb0009; zb0001++ {
				(*z).E[zb0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "struct-from-array", "E", zb0001)
					return
				}
			}
		}
		if zb0004 > 0 {
			zb0004--
			var zb0010 int
			var zb0011 bool
			zb0010, zb0011, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "G")
				return
			}
			if zb0010 > 4 {
				err = msgp.ErrOverflow(uint64(zb0010), uint64(4))
				err = msgp.WrapError(err, "struct-from-array", "G")
				return
			}
			if zb0011 {
				(*z).G = nil
			} else if (*z).G == nil {
				(*z).G = make(map[SortableUint64]uint64, zb0010)
			}
			for zb0010 > 0 {
				var zb0002 SortableUint64
				var zb0003 uint64
				zb0010--
				bts, err = zb0002.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "struct-from-array", "G")
					return
				}
				zb0003, bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "struct-from-array", "G", zb0002)
					return
				}
				(*z).G[zb0002] = zb0003
			}
		}
		if zb0004 > 0 {
			zb0004--
			(*z).H, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "H")
				return
			}
		}
		if zb0004 > 0 {
			zb0004--
			(*z).I, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "I")
				return
			}
		}
		if zb0004 > 0 {
			err = msgp.ErrTooManyArrayFields(zb0004)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array")
				return
			}
		}
	} else {
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0005 {
			(*z) = CanonicalTestStruct{}
		}
		for zb0004 > 0 {
			zb0004--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
			switch string(field) {
			case "a":
				(*z).A, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "A")
					return
				}
			case "b":
				var zb0012 int
				var zb0013 bool
				zb0012, zb0013, bts, err = msgp.ReadMapHeaderBytes(bts)
				if _, ok := err.(msgp.TypeError); ok {
					zb0012, zb0013, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "B")
						return
					}
					if zb0012 > 0 {
						zb0012--
						(*z).B.B1, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "B", "struct-from-array", "B1")
							return
						}
					}
					if zb0012 > 0 {
						zb0012--
						(*z).B.B2, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "B", "struct-from-array", "B2")
							return
						}
					}
					if zb0012 > 0 {
						err = msgp.ErrTooManyArrayFields(zb0012)
						if err != nil {
							err = msgp.WrapError(err, "B", "struct-from-array")
							return
						}
					}
				} else {
					if err != nil {
						err = msgp.WrapError(err, "B")
						return
					}
					if zb0013 {
						(*z).B = struct {
							_struct struct {
							} `codec:",omitempty,omitemptyarray"`
							B1 bool   `codec:"b1,omitempty"`
							B2 string `codec:"b2,omitempty"`
						}{}
					}
					for zb0012 > 0 {
						zb0012--
						field, bts, err = msgp.ReadMapKeyZC(bts)
						if err != nil {
							err = msgp.WrapError(err, "B")
							return
						}
						switch string(field) {
						case "b1":
							(*z).B.B1, bts, err = msgp.ReadBoolBytes(bts)
							if err != nil {
								err = msgp.WrapError(err, "B", "B1")
								return
							}
						case "b2":
							(*z).B.B2, bts, err = msgp.ReadStringBytes(bts)
							if err != nil {
								err = msgp.WrapError(err, "B", "B2")
								return
							}
						default:
							err = msgp.ErrNoField(string(field))
							if err != nil {
								err = msgp.WrapError(err, "B")
								return
							}
						}
					}
				}
			case "c":
				var zb0014 int
				zb0014, err = msgp.ReadBytesBytesHeader(bts)
				if err != nil {
					err = msgp.WrapError(err, "C")
					return
				}
				if zb0014 > 8 {
					err = msgp.ErrOverflow(uint64(zb0014), uint64(8))
					return
				}
				(*z).C, bts, err = msgp.ReadBytesBytes(bts, (*z).C)
				if err != nil {
					err = msgp.WrapError(err, "C")
					return
				}
			case "d":
				(*z).D, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "D")
					return
				}
			case "e":
				var zb0015 int
				zb0015, _, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "E")
					return
				}
				if zb0015 > 2 {
					err = msgp.ArrayError{Wanted: 2, Got: zb0015}
					return
				}
				for zb0001 := 0; zb0001 < zb0015; zb0001++ {
					(*z).E[zb0001], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "E", zb0001)
						return
					}
				}
			case "g":
				var zb0016 int
				var zb0017 bool
				zb0016, zb0017, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "G")
					return
				}
				if zb0016 > 4 {
					err = msgp.ErrOverflow(uint64(zb0016), uint64(4))
					err = msgp.WrapError(err, "G")
					return
				}
				if zb0017 {
					(*z).G = nil
				} else if (*z).G == nil {
					(*z).G = make(map[SortableUint64]uint64, zb0016)
				}
				for zb0016 > 0 {
					var zb0002 SortableUint64
					var zb0003 uint64
					zb0016--
					bts, err = zb0002.UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "G")
						return
					}
					zb0003, bts, err = msgp.ReadUint64Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "G", zb0002)
						return
					}
					(*z).G[zb0002] = zb0003
				}
			case "h":
				(*z).H, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "H")
					return
				}
			case "i":
				(*z).I, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "I")
					return
				}
			default:
				err = msgp.ErrNoField(string(field))
				if err != nil {
					err = msgp.WrapError(err)
					return
				}
			}
		}
	}
	o = bts
	return
}

func (_ *CanonicalTestStruct) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*CanonicalTestStruct)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CanonicalTestStruct) Msgsize() (s int) {
	s = 1 + 2 + msgp.Int64Size + 2 + 1 + 3 + msgp.BoolSize + 3 + msgp.StringPrefixSize + len((*z).B.B2) + 2 + msgp.BytesPrefixSize + len((*z).C) + 2 + msgp.StringPrefixSize + len((*z).D) + 2 + msgp.ArrayHeaderSize
	for zb0001 := range (*z).E {
		s += msgp.StringPrefixSize + len((*z).E[zb0001])
	}
	s += 2 + msgp.MapHeaderSize
	if (*z).G != nil {
		for zb0002, zb0003 := range (*z).G {
			_ = zb0002
			_ = zb0003
			s += 0 + zb0002.Msgsize() + msgp.Uint64Size
		}
	}
	s += 2 + msgp.Int64Size + 2 + msgp.Int64Size
	return
}

// MsgIsZero returns whether this is a zero value
func (z *CanonicalTestStruct) MsgIsZero() bool {
	return ((*z).A == 0) && (((*z).B.B1 == false) && ((*z).B.B2 == "")) && (len((*z).C) == 0) && ((*z).D == "") && ((*z).E == ([2]string{})) && (len((*z).G) == 0) && ((*z).H == 0) && ((*z).I == 0)
}

// MaxSize returns a maximum valid message size for this message type
func CanonicalTestStructMaxSize() (s int) {
	s = 1 + 2 + msgp.Int64Size + 2 + 1 + 3 + msgp.BoolSize + 3
	panic("Unable to determine max size: String type z.B.B2 is unbounded")
	s += 2 + msgp.BytesPrefixSize + 8 + 2
	panic("Unable to determine max size: String type z.D is unbounded")
	s += 2
	// Calculating size of array: z.E
	s += msgp.ArrayHeaderSize
	panic("Unable to determine max size: String type is unbounded for z.E[za0001]")
	s += 2
	s += msgp.MapHeaderSize
	// Adding size of map keys for z.G
	s += 4 * (SortableUint64MaxSize())
	// Adding size of map values for z.G
	s += 4 * (msgp.Uint64Size)
	s += 2 + msgp.Int64Size + 2 + msgp.Int64Size
	return
}

// MarshalMsg implements msgp.Marshaler
func (z SortableUint64) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint64(o, uint64(z))
	return
}

func (_ SortableUint64) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(SortableUint64)
	if !ok {
		_, ok = (z).(*SortableUint64)
	}
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SortableUint64) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint64
		zb0001, bts, err = msgp.ReadUint64Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = SortableUint64(zb0001)
	}
	o = bts
	return
}

func (_ *SortableUint64) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*SortableUint64)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z SortableUint64) Msgsize() (s int) {
	s = msgp.Uint64Size
	return
}

// MsgIsZero returns whether this is a zero value
func (z SortableUint64) MsgIsZero() bool {
	return z == 0
}

// MaxSize returns a maximum valid message size for this message type
func SortableUint64MaxSize() (s int) {
	s = msgp.Uint64Size
	return
}

// MarshalMsg implements msgp.Marshaler
func (z testSlice) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	if z == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendArrayHeader(o, uint32(len(z)))
	}
	for za0001 := range z {
		o = msgp.AppendUint64(o, z[za0001])
	}
	return
}

func (_ testSlice) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(testSlice)
	if !ok {
		_, ok = (z).(*testSlice)
	}
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *testSlice) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 int
	var zb0003 bool
	zb0002, zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0002 > 16 {
		err = msgp.ErrOverflow(uint64(zb0002), uint64(16))
		err = msgp.WrapError(err)
		return
	}
	if zb0003 {
		(*z) = nil
	} else if (*z) != nil && cap((*z)) >= zb0002 {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(testSlice, zb0002)
	}
	for zb0001 := range *z {
		(*z)[zb0001], bts, err = msgp.ReadUint64Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

func (_ *testSlice) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*testSlice)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z testSlice) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize + (len(z) * (msgp.Uint64Size))
	return
}

// MsgIsZero returns whether this is a zero value
func (z testSlice) MsgIsZero() bool {
	return len(z) == 0
}

// MaxSize returns a maximum valid message size for this message type
func TestSliceMaxSize() (s int) {
	// Calculating size of slice: z
	s += msgp.ArrayHeaderSize + ((16) * (msgp.Uint64Size))
	return
}
